### ISSUE TITLE
Backend config failed - "error operation NS SIZE caused by Namespace" 

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/0-stor_v2#38] opened 2021-04-01 01:08 UTC
While testing the latest QSFS bootstrap using a VDC zstor config, I noticed that data wasn't getting pushed to the backend zdbs as expected. The local zdb was giving an error: `"unable to find a valid configuration due to redundancy settings"`. So I tried storing a file directly:

`bin/zstor -c etc/zstor-default.toml store -f mnt/zdbfs/test`

The relevant section of zstor log is shown below. I also tried another zstor config file that points to an older VDC which I've used zstor and zdbfs against with success in the past, and same result. This is with the zstor binary downloaded by the bootstrap, `zstor_v2 0.2.0`, also confirmed same behavior on a build of latest source (ffae44c).

```
2021-03-31 17:52:08 -07:00: DEBUG Finding backend config
2021-03-31 17:52:08 -07:00: DEBUG connecting to zdb at 185.69.167.183:9915
2021-03-31 17:52:08 -07:00: DEBUG connecting to zdb at 185.69.167.183:9912
2021-03-31 17:52:08 -07:00: DEBUG connecting to zdb at 185.69.167.183:9910
2021-03-31 17:52:10 -07:00: DEBUG could not connect to 0-db: ZDB at 185.69.167.183:9915, error operation NS SIZE caused by Namespace only has 0 bytes of space left, but 15 bytes are needed
2021-03-31 17:52:10 -07:00: DEBUG could not connect to 0-db: ZDB at 185.69.167.183:9912, error operation NS SIZE caused by Namespace only has 0 bytes of space left, but 15 bytes are needed
2021-03-31 17:52:10 -07:00: DEBUG could not connect to 0-db: ZDB at 185.69.167.183:9910, error operation NS SIZE caused by Namespace only has 0 bytes of space left, but 15 bytes are needed
2021-03-31 17:52:10 -07:00: DEBUG Backend config failed
2021-03-31 17:52:10 -07:00: DEBUG Finding backend config
2021-03-31 17:52:10 -07:00: DEBUG connecting to zdb at 185.69.167.183:9918
2021-03-31 17:52:10 -07:00: DEBUG connecting to zdb at 185.69.167.183:9919
2021-03-31 17:52:10 -07:00: DEBUG connecting to zdb at 185.69.167.183:9914
2021-03-31 17:52:11 -07:00: DEBUG could not connect to 0-db: ZDB at 185.69.167.183:9914, error operation NS SIZE caused by Namespace only has 0 bytes of space left, but 15 bytes are needed
2021-03-31 17:52:11 -07:00: DEBUG Backend config failed
2021-03-31 17:52:11 -07:00: DEBUG Finding backend config
2021-03-31 17:52:11 -07:00: DEBUG connecting to zdb at 185.69.167.183:9918
2021-03-31 17:52:11 -07:00: DEBUG connecting to zdb at 185.69.167.183:9919
2021-03-31 17:52:11 -07:00: DEBUG connecting to zdb at 185.69.167.183:9913
2021-03-31 17:52:12 -07:00: DEBUG could not connect to 0-db: ZDB at 185.69.167.183:9913, error operation NS SIZE caused by Namespace only has 0 bytes of space left, but 15 bytes are needed
2021-03-31 17:52:12 -07:00: DEBUG Backend config failed
2021-03-31 17:52:12 -07:00: DEBUG Finding backend config
2021-03-31 17:52:12 -07:00: DEBUG connecting to zdb at 185.69.167.183:9918
2021-03-31 17:52:12 -07:00: DEBUG connecting to zdb at 185.69.167.183:9919
2021-03-31 17:52:12 -07:00: DEBUG connecting to zdb at 185.69.167.183:9911
2021-03-31 17:52:13 -07:00: DEBUG could not connect to 0-db: ZDB at 185.69.167.183:9911, error operation NS SIZE caused by Namespace only has 0 bytes of space left, but 15 bytes are needed
2021-03-31 17:52:13 -07:00: DEBUG Backend config failed
2021-03-31 17:52:13 -07:00: DEBUG Finding backend config
2021-03-31 17:52:13 -07:00: DEBUG connecting to zdb at 185.69.167.183:9919
2021-03-31 17:52:13 -07:00: DEBUG connecting to zdb at 185.69.167.183:9916
2021-03-31 17:52:13 -07:00: DEBUG connecting to zdb at 185.69.167.183:9917
2021-03-31 17:52:13 -07:00: DEBUG could not connect to 0-db: ZDB at 185.69.167.183:9916, error operation NS SIZE caused by Namespace only has 0 bytes of space left, but 15 bytes are needed
2021-03-31 17:52:13 -07:00: DEBUG could not connect to 0-db: ZDB at 185.69.167.183:9917, error operation NS SIZE caused by Namespace only has 0 bytes of space left, but 15 bytes are needed
2021-03-31 17:52:13 -07:00: DEBUG Backend config failed
2021-03-31 17:52:13 -07:00: DEBUG Finding backend config
2021-03-31 17:52:13 -07:00: ERROR Could not save file "mnt/zdbfs/test": error during configuration: unable to find a valid configuration due to redundancy settings
2021-03-31 17:52:13 -07:00: ERROR error during configuration: unable to find a valid configuration due to redundancy settings
```

The backends section of the zstor config looks like this, with ascending port numbers and name spaces for the ten storage nodes:

```
[[groups]]

[[groups.backends]]
address = "185.69.167.183:9910"
namespace = "29081-1"
password = "PASS"
```

**Comment by maxux** [comment] 2021-04-01 11:12
Yes, this is `zdb` bug. This is fixed and deployed on `devnet`, but not yet in `testnet`.
If you can generate a configuration using `devnet zdb`, this will be fixed.

We see to update `testnet zdb` soon :)

**Comment by maxux** [comment] 2021-04-01 16:31
Okay, after updating `testnet`, we can confirm this was not just a `zdb` issue, but a `kernel` issue aswell. To keep all features we have, we need to plan a kernel upgrade of all nodes.

We won't do that right now, so we will drop one feature to support current setup and improve that later.

**Comment by scottyeager** [comment] 2021-04-01 22:25
Thanks for the updates, @maxux! Which feature is dependent on the kernel upgrade? And which version of zstor should I rollback to for further testing on testnet?

**Comment by maxux** [comment] 2021-04-01 22:47
Current `zstor` check a value on zdb, which depend on free disk space, in order to know if zdb is usable or not.
This value is not correctly reported by the kernel (caused by a `btrfs` maintenance). A kernel update would fix this, but some `btrfs` maintenance as well, we will integrate that.

You can't just rollback to a previous version, @LeeSmet needs to disable the free space check in order to not exclude faulty node. This is not a required feature, that won't have any bad impact.

**Comment by scottyeager** [comment] 2021-04-01 23:22
All clear. Thanks for the explanation :)

I was able to patch out the free space check and build a version that works against testnet again. So I'm back in business :+1:

**Comment by LeeSmet** [comment] 2021-06-16 14:43
Reluctantly, I disabled the check for now, until the grid is updated to fix the btrfs bug in the kernel.

**Closed** 2021-06-16 14:42 UTC
Labels: type_bug
