### ISSUE TITLE
Adding large file to fuse causes 'could not save value: response failed'

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/0-stor_v2#17] opened 2021-03-08 11:50 UTC
It happens after some parts then along the way

# Logs
```
[       0.016431][+] namespace: loaded: zdbfs-temp
[       0.016508][+] index: populating: /zdb/index/zdbfs-temp/zdb-index-00000
[       0.016516][+] index: healthy
[       0.016524][+] index: active file: /zdb/index/zdbfs-temp/zdb-index-00000
[       0.016581][+] data: active file: /zdb/data/zdbfs-temp/zdb-data-00000
[       0.016655][+] listening on socket 5
[     159.077752][+] index: flushing file before closing
[     169.098515][+] index: closing current index file
[     169.099105][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00066
[     169.099370][+] data: flushing file before closing
[     169.260655][+] data: closing current datafile
[     169.260910][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00066
[     170.048591][+] index: flushing file before closing
[     170.049724][+] index: closing current index file
[     170.049792][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00067
[     170.049967][+] data: flushing file before closing
[     + prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00066
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00066
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00067
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00067
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00068
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00068
170.184250][+] data: closing current datafile
[     170.184865][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00067
[     170.888025][+] index: flushing file before closing
[     170.889190][+] index: closing current index file
[     170.889289][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00068
[     170.889486][+] data: flushing file before closing
[     170.979460][+] data: closing current datafile
[     170.979608][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00068
[     172.131715][+] index: flushing file before closing
[     172.133178][+] index: closing current index file
[     172.133317][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00069
[     172.133638][+] data: flushing file before closing
[     172.258797][+] data: closing current datafile
[     172.259000][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00069
[     173.481529][+] index: flushing file before closing
[     173.485928][+] index: closing current index file
[     173.486007][+] index: active file: + prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00069
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00069
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00070
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00070
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00071
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00071
/zdb/index/zdbfs-data/zdb-index-00070
[     173.486572][+] data: flushing file before closing
[     173.629030][+] data: closing current datafile
[     173.629180][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00070
[     175.055503][+] index: flushing file before closing
[     175.061900][+] index: closing current index file
[     175.061992][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00071
[     175.062191][+] data: flushing file before closing
[     175.226738][+] data: closing current datafile
[     175.226882][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00071
[     176.804878][+] index: flushing file before closing
[     176.805980][+] index: closing current index file
[     176.806047][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00072
[     176.806284][+] data: flushing file before closing
[     176.958466][+] data: closing current datafile
[     176.958629][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00072
[     179.202984][+] index: flushing file before closing+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00072
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00072
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00073
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00073
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0

[     179.209915][+] index: closing current index file
[     179.210004][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00073
[     179.210235][+] data: flushing file before closing
[     179.404149][+] data: closing current datafile
[     179.404325][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00073
[     182.047048][+] index: flushing file before closing
[     182.064208][+] index: closing current index file
[     182.064438][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00074
[     182.064776][+] data: flushing file before closing
[     182.345715][+] data: closing current datafile
[     182.345901][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00074
[     184.500001][+] index: flushing file before closing
[     184.501386][+] index: closing current index file
[     184.501470][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00075
[     184.501661][+] data: flushing file before closing
[     184.732803][+] data: closing current datafile
[     184.732988][+] data: active file: + prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00074
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00074
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00075
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00075
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00076
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00076
Error: "could not save value: response failed"
Error: "could not save value: response failed"
/zdb/data/zdbfs-data/zdb-data-00075
[     187.541765][+] index: flushing file before closing
[     187.548030][+] index: closing current index file
[     187.548146][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00076
[     187.549465][+] data: flushing file before closing
[     188.508079][+] data: closing current datafile
[     188.508225][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00076
[     191.549318][+] index: flushing file before closing
[     191.550406][+] index: closing current index file
[     191.550474][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00077
[     191.550648][+] data: flushing file before closing
[     191.861421][+] data: closing current datafile
[     191.862112][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00077
[     194.882168][+] index: flushing file before closing
[     194.884525][+] index: closing current index file
[     194.884694][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00078
[     194.884987][+] data: flushing file before closing+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00077
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00077
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00078
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00078
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00079
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00079
Error: "could not save value: response failed"

[     195.117620][+] data: closing current datafile
[     195.117757][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00078
[     197.546461][+] index: flushing file before closing
[     197.547927][+] index: closing current index file
[     197.548000][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00079
[     197.551942][+] data: flushing file before closing
[     197.709791][+] data: closing current datafile
[     197.710018][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00079
[     200.666715][+] index: flushing file before closing
[     200.667664][+] index: closing current index file
[     200.667749][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00080
[     200.667953][+] data: flushing file before closing
[     201.006752][+] data: closing current datafile
[     201.006924][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00080
[     204.031755][+] index: flushing file before closing
[     204.041924][+] index: closing current index file
[     204.042006][+] index: active file: + prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00080
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00080
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00081
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00081
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00082
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00082
Error: "could not save value: response failed"
/zdb/index/zdbfs-data/zdb-index-00081
[     204.047593][+] data: flushing file before closing
[     204.251352][+] data: closing current datafile
[     204.251493][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00081
[     206.603054][+] index: flushing file before closing
[     206.604579][+] index: closing current index file
[     206.604651][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00082
[     206.604899][+] data: flushing file before closing
[     206.773433][+] data: closing current datafile
[     206.773591][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00082
[     209.542163][+] index: flushing file before closing
[     209.546137][+] index: closing current index file
[     209.546255][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00083
[     209.546429][+] data: flushing file before closing
[     209.802507][+] data: closing current datafile
[     209.802752][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00083
[     212.373716][+] index: flushing file before closing+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ Error: "could not save value: response failedprefix=/
"
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00083
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00083
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00084
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00084
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0

[     212.376533][+] index: closing current index file
[     212.376608][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00084
[     212.376794][+] data: flushing file before closing
[     212.657868][+] data: closing current datafile
[     212.658024][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00084
[     214.935086][+] index: flushing file before closing
[     214.946317][+] index: closing current index file
[     214.946442][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00085
[     214.946770][+] data: flushing file before closing
[     215.187748][+] data: closing current datafile
[     215.187890][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00085
[     217.921894][+] index: flushing file before closing
[     217.935999][+] index: closing current index file
[     217.936767][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00086
[     217.937178][+] data: flushing file before closing
[     218.197965][+] data: closing current datafile
[     218.198129][+] data: active file: + prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00085
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00085
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00086
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00086
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00087
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00087
Error: "could not save value: response failed"
/zdb/data/zdbfs-data/zdb-data-00086
[     221.020268][+] index: flushing file before closing
[     221.039163][+] index: closing current index file
[     221.039389][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00087
[     221.039606][+] data: flushing file before closing
[     221.298207][+] data: closing current datafile
[     221.298379][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00087
[     223.857353][+] index: flushing file before closing
[     223.858436][+] index: closing current index file
[     223.858518][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00088
[     223.858741][+] data: flushing file before closing
[     224.051874][+] data: closing current datafile
[     224.052019][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00088
[     226.436527][+] index: flushing file before closing
[     226.437917][+] index: closing current index file
[     226.437988][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00089
[     226.438223][+] data: flushing file before closing+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00088
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00088
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00089
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00089
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
Error: "could not save value: response failed"
+++ dirname /zdb/data/zdbfs-data/zdb-data-00090
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00090

[     226.627663][+] data: closing current datafile
[     226.627808][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00089
[     229.305468][+] index: flushing file before closing
[     229.306410][+] index: closing current index file
[     229.306491][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00090
[     229.306686][+] data: flushing file before closing
[     229.518184][+] data: closing current datafile
[     229.518329][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00090
[     232.049719][+] index: flushing file before closing
[     232.051477][+] index: closing current index file
[     232.051580][+] index: active file: /zdb/index/zdbfs-data/zdb-index-00091
[     232.053313][+] data: flushing file before closing
[     232.269735][+] data: closing current datafile
[     232.269919][+] data: active file: /zdb/data/zdbfs-data/zdb-data-00091
[     234.517930][+] index: flushing file before closing
[     234.519460][+] index: closing current index file
[     234.519585][+] index: active file: + prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0+ 
prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00091
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00091
Error: "could not save value: response failed"
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
Error: + zstorbin=//bin/zstor
+ "could not save value: response failed'[' "
jump-index == jump-index ']'
+ exit 0
+ prefix=/
+ action=jump-data
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00092
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00092
+ prefix=/
+ action=jump-index
+ instance=tcp://:::9900
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-index == jump-index ']'
+ exit 0
.
.
.
+ zstorconf=//etc/zstor-default.toml
+ zstorbin=//bin/zstor
+ '[' jump-data == jump-index ']'
+ '[' jump-data == jump-data ']'
+++ dirname /zdb/data/zdbfs-data/zdb-data-00130
++ basename /zdb/data/zdbfs-data
+ namespace=zdbfs-data
+ '[' zdbfs-data == zdbfs-temp ']'
+ //bin/zstor -c //etc/zstor-default.toml store --file /zdb/data/zdbfs-data/zdb-data-00130
Error: "could not save value: response failed"
Error: "could not save value: response failed"
Error: "could not save value: response failed"
Error: "could not save value: response failed"
Error: "could not save value: response failed"
Error: "could not save value: response failed"
Error: "could not save value: response failed"
Error: "could not save value: response failed"
```

# Zstor config
```
k3os-4071 [~]$ cat /etc/zstor-default.toml 
data_shards = 2
parity_shards = 1
redundant_groups = 0
redundant_nodes = 0

[encryption]
algorithm = "AES"
key = "3030303030303030303030303030303030303030303030303132333435363738"

[compression]
algorithm = "snappy"

[meta]
type = "etcd"

[meta.config]
endpoints = ["https://etcd-34430.webg2dev.grid.tf:2379"]
prefix = "node-34430"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:3c0d:23ff:fe58:98ef]:9900"
namespace = "34415-1"
password = "12345678"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:b814:91ff:fe72:d44e]:9900"
namespace = "34416-1"
password = "12345678"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:3c0d:23ff:fe58:98ef]:9900"
namespace = "34417-1"
password = "12345678"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:c46:cff:fe32:39ae]:9900"
namespace = "34418-1"
password = "12345678"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:3c0d:23ff:fe58:98ef]:9900"
namespace = "34419-1"
password = "12345678"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:b814:91ff:fe72:d44e]:9900"
namespace = "34420-1"
password = "12345678"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:9452:82ff:fe58:e440]:9900"
namespace = "34421-1"
password = "12345678"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:c46:cff:fe32:39ae]:9900"
namespace = "34422-1"
password = "12345678"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:b814:91ff:fe72:d44e]:9900"
namespace = "34423-1"
password = "12345678"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:c46:cff:fe32:39ae]:9900"
namespace = "34424-1"
password = "12345678"
```

# maybe related to https://github.com/threefoldtech/0-stor_v2/issues/16

**Comment by waleedhammam** [comment] 2021-03-08 11:59
also Using http and ip worked ok

**Comment by maxux** [comment] 2021-03-08 12:05
We need @LeeSmet to improve error message to see where that comes from, but title can be confusing, I don't think it's « large file » the issue, it's maybe the amount of concurrent connection or namespace not available, or etcd not accepting keys after a while.

**Comment by LeeSmet** [comment] 2021-03-08 13:26
duplicate of #16, closing this in favor of that one

**Closed by LeeSmet** 2021-03-08 13:26 UTC
Labels: type_bug
