### ISSUE TITLE
New backends added with SIGUSR1 aren't included with Prometheus metrics

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/0-stor_v2#120] opened 2024-07-11 00:45 UTC
I updated the config file of a zstor process running in monitor mode and reloaded the config by issuing `SIGUSR1`. The new backends now show up when I run the `status` command, but they have not been added to the Prometheus metrics.

Compare:

```console
# zstor -c /etc/zstor-default.toml status
+---------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| backend                                                             | reachable | objects | used space | free space | usage percentage |
+=====================================================================+===========+=========+============+============+==================+
| [44a:5fd6:b716:d147:f5ae:7088:a381:4976]:9900 - 81-42998-node1meta0 | No        |       - |          - |          - |                - |
+---------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| [4b8:280d:e777:5252:f985:19cc:dcfd:7624]:9900 - 81-42999-node3meta0 | Yes       |      93 |      44208 | 1073741824 |                0 |
+---------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| [4d0:6235:9b0e:328b:b0f8:4c1c:5ed8:b673]:9900 - 81-43000-node5meta0 | Yes       |      93 |      44208 | 1073741824 |                0 |
+---------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| [564:7d94:d5cc:f37b:4783:35d6:6b37:a40]:9900 - 81-43001-node7meta0  | Yes       |      93 |      44208 | 1073741824 |                0 |
+---------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
+----------------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| backend                                                                    | reachable | objects | used space | free space | usage percentage |
+============================================================================+===========+=========+============+============+==================+
| [44a:5fd6:b716:d147:f5ae:7088:a381:4976]:9900 - 81-43002-node1backend0     | No        |       - |          - |          - |                - |
+----------------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| [4b8:280d:e777:5252:f985:19cc:dcfd:7624]:9900 - 81-43003-node3backend0     | Yes       |     620 | 1071916880 | 1073741824 |               99 |
+----------------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| [4d0:6235:9b0e:328b:b0f8:4c1c:5ed8:b673]:9900 - 81-43004-node5backend0     | Yes       |     620 | 1071916880 | 1073741824 |               99 |
+----------------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| [564:7d94:d5cc:f37b:4783:35d6:6b37:a40]:9900 - 81-43005-node7backend0      | Yes       |     620 | 1071916880 | 1073741824 |               99 |
+----------------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| [44a:5fd6:b716:d147:f5ae:7088:a381:4976]:9900 - 81-43148-node1backendsnew0 | No        |       - |          - |          - |                - |
+----------------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| [4b8:280d:e777:5252:f985:19cc:dcfd:7624]:9900 - 81-43149-node3backendsnew0 | Yes       |       0 |          0 | 1073741824 |                0 |
+----------------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| [4d0:6235:9b0e:328b:b0f8:4c1c:5ed8:b673]:9900 - 81-43150-node5backendsnew0 | Yes       |       0 |          0 | 1073741824 |                0 |
+----------------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
| [564:7d94:d5cc:f37b:4783:35d6:6b37:a40]:9900 - 81-43151-node7backendsnew0  | Yes       |       0 |          0 | 1073741824 |                0 |
+----------------------------------------------------------------------------+-----------+---------+------------+------------+------------------+
```

```
# TYPE data_disk_freespace_bytes gauge
data_disk_freespace_bytes{address="[44a:5fd6:b716:d147:f5ae:7088:a381:4976]:9900",backend_type="data",namespace="81-43002-node1backend0"} 996966887424
data_disk_freespace_bytes{address="[4b8:280d:e777:5252:f985:19cc:dcfd:7624]:9900",backend_type="data",namespace="81-43003-node3backend0"} 2997354729472
data_disk_freespace_bytes{address="[4b8:280d:e777:5252:f985:19cc:dcfd:7624]:9900",backend_type="meta",namespace="81-42999-node3meta0"} 2997354729472
data_disk_freespace_bytes{address="[4d0:6235:9b0e:328b:b0f8:4c1c:5ed8:b673]:9900",backend_type="data",namespace="81-43004-node5backend0"} 2997354999808
data_disk_freespace_bytes{address="[4d0:6235:9b0e:328b:b0f8:4c1c:5ed8:b673]:9900",backend_type="meta",namespace="81-43000-node5meta0"} 2997354999808
data_disk_freespace_bytes{address="[564:7d94:d5cc:f37b:4783:35d6:6b37:a40]:9900",backend_type="data",namespace="81-43005-node7backend0"} 2997354733568
data_disk_freespace_bytes{address="[564:7d94:d5cc:f37b:4783:35d6:6b37:a40]:9900",backend_type="meta",namespace="81-43001-node7meta0"} 2997354733568
```

**Comment by scottyeager** [comment] 2024-10-01 21:19
Further observation here is that I realized when calling `status`, backends are shown in the output if and only if they are present in the config file. There's no relation to which backends zstor actually has in its live config.

I was able to confirm that after a `SIGUSR1` zstor is using the new backends from the config file, based on the fact that it's uploading data to them. However, the behavior of the new backends not showing up on the metrics endpoint in reproduced in my test today too.

**Comment by iwanbk** [comment] 2024-11-11 03:24
Hi @Mik-TF 
The plan was i started to check it last Wednesday, but i got sick.
I start to check it today, but please give me some time to familiarize with the repo.

I think this issue and #123 are a good start.

**Comment by Mik-TF** [comment] 2024-11-11 05:14
Of course! I hope you're feeling better and that you heal quickly :)

Good idea to take some time working out the repo. Please let us know what you find and don't hesitate to update the issue + ask for feedback if you deem it relevant.

Fixing zstor will greatly improve QSFS functionalities. Thanks for checking this.

**Comment by iwanbk** [comment] 2024-11-12 04:05
> I updated the config file of a zstor process running in monitor mode and reloaded the config by issuing SIGUSR1. The new backends now show up when I run the status command, but they have not been added to the Prometheus metrics.

I can reproduce this and found the issue.
It is because when the `zstor monitor` received the SIGUSR1, it indeed do some config reload, but unfortunately the prometheus handler, which created at https://github.com/threefoldtech/0-stor_v2/blob/b5e7a3c0f71e1ab93fb1deb0e5279f0f4654d735/zstor/src/main.rs#L489 is not reloaded

 I think it is a valid bug that should be fixed

**Comment by iwanbk** [comment] 2024-11-12 06:26
about this comment https://github.com/threefoldtech/0-stor_v2/issues/120#issuecomment-2469548288, this part

> but unfortunately the prometheus handler, which created at .... is not reloaded

this part might not be the root cause

> I think it is a valid bug that should be fixed

but still a bug. I'm checking it now

**Comment by iwanbk** [comment] 2024-11-13 04:31
I found the issue, and wrote some fix PoC.
New backend can be included in the prometheus.

But when we remove the backend from the config file, the removed backend still in prometheus.
I'm checking it now.

**Comment by iwanbk** [comment] 2024-11-13 08:15
@scottyeager @Mik-TF 
i've sent the PR #126 to fix this 

Regarding the `zstor status`, if still needed, please create another issue because it is an entirely different thing and might not a real issue as i explained at https://github.com/threefoldtech/0-stor_v2/issues/120#issuecomment-2469553335

**Closed** 2024-11-13 10:56 UTC

**Comment by scottyeager** [comment] 2024-11-14 03:01
Thanks @iwanbk. I will test.

> Regarding the zstor status, if still needed, please create another issue because it is an entirely different thing and might not a real issue as i explained at https://github.com/threefoldtech/0-stor_v2/issues/120#issuecomment-2469553335

I agree it's a separate issue. I also agree that changing the behavior of the existing command might not be the best approach. It still somewhat bugs me that we don't have a command to inspect the loaded config in the `monitor` process.

**Comment by scottyeager** [comment] 2024-11-16 00:38
I have verified. The Prometheus metrics now update appropriately after `SIGUSR1`.
