### ISSUE TITLE
Data files are not restore due to insufficient shards (and it shouldn't?)

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/0-stor_v2#76] opened 2021-11-08 09:40 UTC
The image `omarelawady/qsfs` is pushed for reproducing. 
I tried this locally:
```bash
../bin/zdb2 --version # v2.0.0-rc6
../bin/zdb2 --datasize 10 --mode seq --port 8800 --verbose
../bin/zdb2 --datasize 10 --mode user --port 9900 --verbose
mkdir -p /qsfs /qsfs-data /qsfs-index
./script.sh
docker run -ti --rm --name qsfs --privileged --device /dev/fuse -v /qsfs-index:/data/index -v /qsfs-data:/data/data --mount type=bind,source=/qsfs,target=/mnt,bind-propagation=rshared omarelawady/qsfs /sbin/zinit init
```
script.sh:
```bash
#!/bin/bash

cat << EOF | redis-cli -p 9900
nsdel meta-1
nsdel meta-2
nsdel meta-3
nsdel meta-4
NSNEW meta-1
NSNEW meta-2
NSNEW meta-3
NSNEW meta-4
EOF

cat << EOF | redis-cli -p 8800
nsdel data-1
nsdel data-2
nsdel data-3
nsdel data-4
NSNEW data-1
NSNEW data-2
NSNEW data-3
NSNEW data-4
EOF
```

qsfs is mounted as expected on /qsfs. After `dd if=/dev/urandom of=/qsfs/hi bs=1M count=300` two data files are created on `/qsfs-data/zdbfs-data/d0` and `/qsfs-data/zdbfs-data/d1`. The container and zdbs logs show that zstor is called and the data is uploaded (also the sizes of the namespaces are increased). I deleted d0 and d1 and tried to `head /qsfs/hi -c 1`, I got Input/Output error and this error is shown:
```
+ /bin/zstor -c /data/zstor.toml store -s --file /data/data/zdbfs-data/d0
+ exit 0
+ action=missing-data
+ instance=tcp://:::9900
+ zstorconf=/data/zstor.toml
+ zstorbin=/bin/zstor
+ '[' missing-data == ready ']'
+ '[' missing-data == jump-index ']'
+ '[' missing-data == jump-data ']'
+ '[' missing-data == missing-data ']'
+ /bin/zstor -c /data/zstor.toml retrieve --file /data/data/zdbfs-data/d0
Zstor error: error during encoding: Error in encoder/decoder: Operation: RECONSTRUCT, The number of shards present is smaller than number of parity shards, cannot reconstruct missing shards
[     120.075276][-] /data/data/zdbfs-data/d0: No such file or directory
[     120.075288][-] command: get: cannot read payload
[-] zdb: zdbfs-data: get: error: Internal Error
```

zstor.toml:
```
minimal_shards = 1 
expected_shards = 2 
redundant_groups = 0
redundant_nodes = 0
max_zdb_data_dir_size = 256
socket = "/var/run/zstor.sock"
prometheus_port = 9100
zdbfs_mountpoint = "/mnt"
zdb_data_dir_path = "/data/data/zdbfs-data"
zdb_index_dir_path = "/data/index/zdbfs-data"

[encryption]
  algorithm = "AES"
  key = "4d778ba3216e4da4231540c92a55f06157cabba802f9b68fb0f78375d2e825af"

[meta]
  type = "zdb"
  [meta.config]
    prefix = "hamada"
    [meta.config.encryption]
      algorithm = "AES"
      key = "4d778ba3216e4da4231540c92a55f06157cabba802f9b68fb0f78375d2e825af"

    [[meta.config.backends]]
      address = "172.17.0.1:9900"
      namespace = "meta-1"

    [[meta.config.backends]]
      address = "172.17.0.1:9900"
      namespace = "meta-2"

    [[meta.config.backends]]
      address = "172.17.0.1:9900"
      namespace = "meta-3"

    [[meta.config.backends]]
      address = "172.17.0.1:9900"
      namespace = "meta-4"

[[groups]]

  [[groups.backends]]
    address = "172.17.0.1:8800"
    namespace = "data-1"

  [[groups.backends]]
    address = "172.17.0.1:8800"
    namespace = "data-2"

  [[groups.backends]]
    address = "172.17.0.1:8800"
    namespace = "data-3"

  [[groups.backends]]
    address = "172.17.0.1:8800"
    namespace = "data-4"

[compression]
  algorithm = "snappy"
```

**Comment by OmarElawady** [comment] 2021-11-08 10:27
zstor log:
```
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:9900
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:9900
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:9900
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:9900
2021-11-08 10:25:34 +00:00: WARN NopExplorer started, automatic capacity managment is disabled
2021-11-08 10:25:34 +00:00: DEBUG Backend manager actor started, loading backends to monitor
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:9900
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:9900
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:9900
2021-11-08 10:25:34 +00:00: DEBUG connecting to zdb at 172.17.0.1:9900
2021-11-08 10:25:35 +00:00: WARN Could not get 0-db-fs stats: Not a tty (os error 25)
2021-11-08 10:25:36 +00:00: WARN Could not get 0-db-fs stats: Not a tty (os error 25)
2021-11-08 10:25:37 +00:00: WARN Could not get 0-db-fs stats: Not a tty (os error 25)
2021-11-08 10:25:47 +00:00: DEBUG Handling new client connection from (unnamed)
2021-11-08 10:25:47 +00:00: DEBUG encoding file "/tmp/zdb.hook.oUdi7nk6.tmp/i0" with key path "/data/index/zdbfs-data/i0"
2021-11-08 10:25:47 +00:00: DEBUG file checksum: 616f7128459c5f0d20dabbae905c5c3a ("/tmp/zdb.hook.oUdi7nk6.tmp/i0")
2021-11-08 10:25:47 +00:00: DEBUG Finding backend config
2021-11-08 10:25:47 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:25:47 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:25:47 +00:00: DEBUG found valid backend configuration
2021-11-08 10:25:47 +00:00: DEBUG Saving metadata for key /hamada/meta/30fedb5562c093176136eda518fdb0d9
2021-11-08 10:25:47 +00:00: DEBUG Writing data to zdb metastore
2021-11-08 10:25:47 +00:00: DEBUG Handling new client connection from (unnamed)
2021-11-08 10:25:47 +00:00: DEBUG encoding file "/data/data/zdbfs-data/d0" with key path "/data/data/zdbfs-data/d0"
2021-11-08 10:25:48 +00:00: DEBUG file checksum: c224c198f66f22bb11cf6a310c011513 ("/data/data/zdbfs-data/d0")
2021-11-08 10:25:49 +00:00: DEBUG Finding backend config
2021-11-08 10:25:49 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:25:49 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:25:49 +00:00: DEBUG found valid backend configuration
2021-11-08 10:25:50 +00:00: DEBUG Saving metadata for key /hamada/meta/b76d074c120d900d6f3065e45bdad1a7
2021-11-08 10:25:50 +00:00: DEBUG Writing data to zdb metastore
2021-11-08 10:26:32 +00:00: DEBUG Handling new client connection from (unnamed)
2021-11-08 10:26:32 +00:00: DEBUG Loading metadata for key /hamada/meta/b76d074c120d900d6f3065e45bdad1a7
2021-11-08 10:26:32 +00:00: DEBUG Reading data from zdb metastore for key /hamada/meta/b76d074c120d900d6f3065e45bdad1a7
2021-11-08 10:26:32 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:26:32 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:26:32 +00:00: WARN could not download shard 0: error during storage: ZDB at 172.17.0.1:8800, error operation READ caused by missing key 01000000
2021-11-08 10:26:32 +00:00: WARN could not download shard 1: error during storage: ZDB at 172.17.0.1:8800, error operation READ caused by missing key 00000000
2021-11-08 10:26:32 +00:00: DEBUG Handling new client connection from (unnamed)
2021-11-08 10:26:32 +00:00: DEBUG Loading metadata for key /hamada/meta/b76d074c120d900d6f3065e45bdad1a7
2021-11-08 10:26:32 +00:00: DEBUG Reading data from zdb metastore for key /hamada/meta/b76d074c120d900d6f3065e45bdad1a7
2021-11-08 10:26:32 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:26:32 +00:00: DEBUG connecting to zdb at 172.17.0.1:8800
2021-11-08 10:26:32 +00:00: WARN could not download shard 0: error during storage: ZDB at 172.17.0.1:8800, error operation READ caused by missing key 01000000
2021-11-08 10:26:32 +00:00: WARN could not download shard 1: error during storage: ZDB at 172.17.0.1:8800, error operation READ caused by missing key 00000000
2021-11-08 10:26:34 +00:00: DEBUG checking data dir size
2021-11-08 10:26:34 +00:00: DEBUG Directory "/data/data/zdbfs-data" is within size limits (0 < 268435456)
```

**Comment by maxux** [comment] 2021-11-08 12:45
Using --datasize 10 is _really_ not a good idea. Please use at least > 1048576 (I'll make this mandatory in next version)

**Comment by LeeSmet** [comment] 2021-11-08 15:25
```
../bin/zdb2 --version # v2.0.0-rc6
../bin/zdb2 --datasize 10 --mode seq --port 8800 --verbose
../bin/zdb2 --datasize 10 --mode user --port 9900 --verbose
mkdir -p /qsfs /qsfs-data /qsfs-index
./script.sh
docker run -ti --rm --name qsfs --privileged --device /dev/fuse -v /qsfs-index:/data/index -v /qsfs-data:/data/data --mount type=bind,source=/qsfs,target=/mnt,bind-propagation=rshared omarelawady/qsfs /sbin/zinit init
```

Are the 2 zdb's started from the same location? If so, they might use the same index/data directories, which could cause trouble (especially if files get deleted). Can you retry by passing explicit `--data` and  `--index` flags pointing to different directories for each 0-db?

**Comment by maxux** [comment] 2021-11-08 15:27
@LeeSmet you pointed an interesting point ! I think I should add some lock for zdb aswell to avoid double zdb using same directories.

**Comment by OmarElawady** [comment] 2021-11-08 15:37
Yeah I didn't mention that in the issue but I created two separate directories, one for the data and one for the metadata.

**Comment by LeeSmet** [comment] 2021-11-08 15:50
Ok, from the logs, it seems that a key is missing in the data 0-db (even though they key is returned when the data is saved). I'll try to reproduce locally

**Comment by LeeSmet** [comment] 2021-11-09 09:54
Ok so the issue is that in zdb v2, sequential keys are 64 bit integers instead of 32 bit integers. 0-stor decodes the raw bytes to this integer type. When retrieving the data, the key is encoded again, but it will be too short. Solutions would be to either not interpret the key and work with the raw bytes, or to create an enum which is either a 32 or 64 bit key, which is decided at runtime based on the length of the returned key.

**Comment by LeeSmet** [comment] 2021-11-09 10:47
Issue is fixed on master, will create a release later. Since the key type changed, and we use strongly typed metadata, this WILL break backward compatibility with older versions of 0-stor.

**Closed** 2021-11-09 10:47 UTC
Labels: type_bug
